import Config

# Configure your database
config :app, App.Repo,
  # database: Path.expand("../app_dev.db", Path.dirname(__ENV__.file)),
  # pool_size: 5,
  # show_sensitive_data_on_connection_error: true
  username: "dev",
  password: "xubuntudb",
  database: "groups_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :app, AppWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # http: [ip: {127, 0, 0, 1}, port: 4000],
  http: [ip: {0, 0, 0, 0}, port: (System.get_env("PORT") || "4000") |> String.to_integer()],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "JjUQiLdNm9cqx7gwRRZK+NNwpaJFLode2lN4bU0Mn4WtCVLDYZb4g7yioMkqtsYq",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    yarn: [
      "tailwindcss",
      "--postcss",
      "--input=_css/tailwind.css",
      "--output=css/tailwind.css",
      cd: Path.expand("../assets", __DIR__)
    ],
    yarn: [
      "sass",
      "-q",
      "_css/custom/index.scss:css/custom.css",
      "_css/icons.scss:css/icons.css",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# Configures the mailer
# Host:
# smtp.mailtrap.io
# Port:
# 25 or 465 or 587 or 2525
# Username:
# c7cf0277efd293
# Password:
# 9ef4cc4b393eec
# Auth:
# PLAIN, LOGIN and CRAM-MD5
# TLS:
# Optional (STARTTLS on all ports)
# config :app, App.Mailer, adapter: Swoosh.Adapters.Local
config :app, App.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "smtp.mailtrap.io",
  username: "c7cf0277efd293",
  password: "9ef4cc4b393eec",
  # ssl: true,
  # tls: :always,
  tls: :never,
  auth: :always,
  port: 2525,
  # dkim: [
  #   s: "default",
  #   d: "domain.com",
  #   private_key: {:pem_plain, File.read!("priv/keys/domain.private")}
  # ],
  retries: 2,
  no_mx_lookups: false

# Swoosh API client is needed for adapters other than SMTP.
config :swoosh, :api_client, false

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :app, AppWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"assets/_css",
      ~r"assets/js",
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/app_web/(live|views)/.*(ex)$",
      ~r"lib/app_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
